//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mounts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mounts.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        internal static string Documentation_Button_Label {
            get {
                return ResourceManager.GetString("Documentation_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Flying Mount Choice.
        /// </summary>
        internal static string Setting_DefaultFlyingMountChoice {
            get {
                return ResourceManager.GetString("Setting_DefaultFlyingMountChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Mount button behaviour.
        /// </summary>
        internal static string Setting_DefaultMountBehaviour {
            get {
                return ResourceManager.GetString("Setting_DefaultMountBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Mount Binding.
        /// </summary>
        internal static string Setting_DefaultMountBinding {
            get {
                return ResourceManager.GetString("Setting_DefaultMountBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Mount Choice.
        /// </summary>
        internal static string Setting_DefaultMountChoice {
            get {
                return ResourceManager.GetString("Setting_DefaultMountChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Water Mount Choice.
        /// </summary>
        internal static string Setting_DefaultWaterMountChoice {
            get {
                return ResourceManager.GetString("Setting_DefaultWaterMountChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display module on loading screen.
        /// </summary>
        internal static string Setting_DisplayModuleOnLoadingScreen {
            get {
                return ResourceManager.GetString("Setting_DisplayModuleOnLoadingScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Mount queuing.
        /// </summary>
        internal static string Setting_DisplayMountQueueing {
            get {
                return ResourceManager.GetString("Setting_DisplayMountQueueing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount automatically after loading screen.
        /// </summary>
        internal static string Setting_MountAutomaticallyAfterLoadingScreen {
            get {
                return ResourceManager.GetString("Setting_MountAutomaticallyAfterLoadingScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not send keybind to game.
        /// </summary>
        internal static string Setting_MountBlockKeybindFromGame {
            get {
                return ResourceManager.GetString("Setting_MountBlockKeybindFromGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Type.
        /// </summary>
        internal static string Setting_MountDisplay {
            get {
                return ResourceManager.GetString("Setting_MountDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display corner icons.
        /// </summary>
        internal static string Setting_MountDisplayCornerIcons {
            get {
                return ResourceManager.GetString("Setting_MountDisplayCornerIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display manual icons.
        /// </summary>
        internal static string Setting_MountDisplayManualIcons {
            get {
                return ResourceManager.GetString("Setting_MountDisplayManualIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Dragging (White Box).
        /// </summary>
        internal static string Setting_MountDrag {
            get {
                return ResourceManager.GetString("Setting_MountDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Icon Width.
        /// </summary>
        internal static string Setting_MountImgWidth {
            get {
                return ResourceManager.GetString("Setting_MountImgWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Location.
        /// </summary>
        internal static string Setting_MountLoc {
            get {
                return ResourceManager.GetString("Setting_MountLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Opacity.
        /// </summary>
        internal static string Setting_MountOpacity {
            get {
                return ResourceManager.GetString("Setting_MountOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the mount in the center of the radial.
        /// </summary>
        internal static string Setting_MountRadialCenterMountBehavior {
            get {
                return ResourceManager.GetString("Setting_MountRadialCenterMountBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radial Icon Opacity.
        /// </summary>
        internal static string Setting_MountRadialIconOpacity {
            get {
                return ResourceManager.GetString("Setting_MountRadialIconOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radial Icon Size.
        /// </summary>
        internal static string Setting_MountRadialIconSizeModifier {
            get {
                return ResourceManager.GetString("Setting_MountRadialIconSizeModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radial radius.
        /// </summary>
        internal static string Setting_MountRadialRadiusModifier {
            get {
                return ResourceManager.GetString("Setting_MountRadialRadiusModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes center mount from radial.
        /// </summary>
        internal static string Setting_MountRadialRemoveCenterMount {
            get {
                return ResourceManager.GetString("Setting_MountRadialRemoveCenterMount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radial spawn at mouse.
        /// </summary>
        internal static string Setting_MountRadialSpawnAtMouse {
            get {
                return ResourceManager.GetString("Setting_MountRadialSpawnAtMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radial start angle.
        /// </summary>
        internal static string Setting_MountRadialStartAngle {
            get {
                return ResourceManager.GetString("Setting_MountRadialStartAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingame KeyBind to toggle action camera.
        /// </summary>
        internal static string Setting_MountRadialToggleActionCameraKeyBinding {
            get {
                return ResourceManager.GetString("Setting_MountRadialToggleActionCameraKeyBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Orientation.
        /// </summary>
        internal static string Setting_Orientation {
            get {
                return ResourceManager.GetString("Setting_Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Button_Label {
            get {
                return ResourceManager.GetString("Settings_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        internal static string Window_GeneralSettingsTab {
            get {
                return ResourceManager.GetString("Window_GeneralSettingsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Settings.
        /// </summary>
        internal static string Window_IconSettingsTab {
            get {
                return ResourceManager.GetString("Window_IconSettingsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radial Settings.
        /// </summary>
        internal static string Window_RadialSettingsTab {
            get {
                return ResourceManager.GetString("Window_RadialSettingsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support me.
        /// </summary>
        internal static string Window_SupportMeTab {
            get {
                return ResourceManager.GetString("Window_SupportMeTab", resourceCulture);
            }
        }
    }
}
