name: Update Discussion based on readme

on:
  push:
    branches:
      - main

jobs:
  update-discussion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Modify readme content and escape
        id: readme-content
        shell: bash
        run: |
          #!/bin/bash
          
          readme_content=$(cat README.md)
          modified_content=$(echo "$readme_content" | sed 's|!\[\](\./|![](https://raw.githubusercontent.com/${{ github.event.repository.owner.name }}/${{ github.event.repository.name }}/main/|g')
          modified_content=$(echo "$modified_content" | sed 's|\\|\\\\|g')
          modified_content=$(echo "$modified_content" | sed 's|\"|\\"|g')
          modified_content=$(echo "$modified_content" | sed ':a;N;$!ba;s/\n/\\n/g')
          echo "content=$modified_content" >> $GITHUB_OUTPUT

      - name: Find discussion global ID
        id: find-discussion
        uses: octokit/graphql-action@v2.x
        with:
          query: |
            query FindDiscussionIds($owner: String!, $repo: String!) {
              repository(owner:$owner, name:$repo) {
                pinnedDiscussions(first:1) {
                  nodes {
                    discussion {
                      id
                    }
                  }
                }
              }
            }
          variables: |
            {
              "owner": "${{ github.event.repository.owner.name }}",
              "repo": "${{ github.event.repository.name }}"
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Update discussion
        uses: octokit/graphql-action@v2.x
        with:
          title: "Introduction"
          body: "somebody variable"
          query: |
            mutation updateDiscussion($discussionid:ID!, $body:String!) {
              updateDiscussion(
                input: {
                  discussionId: $discussionid, 
                  body: $body 
                }
              ) {
                discussion {
                  id
                }
              }
            }
          variables: |
            {
              "body": "${{ steps.readme-content.outputs.content }}",
              "discussionid": "${{ fromJson(steps.find-discussion.outputs.data).repository.pinneddiscussions.nodes[0].discussion.id }}"
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Call webhook
        id: readme-content
        shell: bash
        run: |
          #!/bin/bash
          curl https://ssrd.blishhud.com/api/public/webhook/updatemoduleprofile?id=46f1a0da-85ef-4145-b4c6-02455e769888