name: Update Discussion based on readme

on:
  push:
    branches:
      - main

jobs:
  update-discussion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Modify readme content and update discussion
        id: readme-content
        shell: bash
        run: |
          #!/bin/bash
          
          readme_content=$(cat README_test.md)
          echo "readme_content: $readme_content"
          
          echo "github.repository_owner: ${{ github.repository_owner }}"
          echo "github.repository: ${{ github.repository }}"
          modified_content=${readme_content//"![](./"/"![](https://raw.githubusercontent.com/${{ github.repository_owner }}/${{ github.repository }}/main/"}
          echo "modified_content: $modified_content"

          # discussion_id=$(curl -s -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/discussions" | jq -r '.[0].id')
          
          curl -X PATCH \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"body": "'"${{ steps.readme-content.outputs.content }}"'"}' \
            "https://api.github.com/repos/${{ github.repository }}/discussions/59"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
